Repository DUNE-DAQ/flxlibs, pull requests merged in 2022-10, with the labels that each got.

#81 Adding shortchunk handler
  include/flxlibs/AvailableParserOperations.hpp
  src/CreateElink.hpp
Labels: feature

#86 Properly add physical card and SLR ID as name suffix
  src/CardWrapper.cpp
Labels: bug

#88 Configuring EMU with DUNE-WIB chunk size
  docs/Configuring-the-EMU.md
Labels: documentation
