Repository DUNE-DAQ/flxlibs, pull requests merged in 2022-11, with the labels that each got.

#93 Ensure locking card's dma
  src/CardWrapper.cpp
Labels: bug

#99 Version bump
  CMakeLists.txt
Labels: version change

#83 Roland sipos/daphne stream frame
  src/CreateElink.hpp
  src/ElinkConcept.hpp
Labels: feature

#101 Sbhuller/flx cc
  plugins/FelixCardController.cpp
  python/flxlibs/cardcontrollerapp/cardcontrollerapp_gen.py
  schema/flxlibs/confgen.jsonnet
  schema/flxlibs/felixcardcontroller.jsonnet
  scripts/felixcardcontrollerconf_gen.py
  scripts/flx.json
  src/CardControllerWrapper.cpp
  src/CardControllerWrapper.hpp
Labels: feature
